# Backend
x-backend-base: &backend_base 
  build: 
    context: ./backend
    dockerfile: Dockerfile.test
  env_file: 
    - path: .env
      required: false
  environment:
    - JWT_ALGORITHM=HS256
    - JWT_ACCESS_SECRET=STUFRZH-MKLFj4j-6c9Z50WNWkvd9uqiWQJOpeCtI9Q
    - MFA_ENCRYPTION_KEY=7CrUl1rG4NBNk4bSV2uU7RW79Z_dRdvrrZn3Eqgytqg=
    - ALLOWED_ORIGINS=http://localhost:8000,http://localhost:3000
    - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-sk-ant-dummy-key-for-testing}
    - APP_NAME=testing
    - APP_URL=http://localhost:8001 
    - SMTP_EMAIL=email@exmaple.com
    - SMTP_PASSWORD=password
    - SMTP_SERVER=mail.privateemail.com
    - SUPPORT_EMAIL=example@email.com
    - ENVIRONMENT=Testing
    - POSTGRES_HOST=postgres-test
    - POSTGRES_PORT=5432
    - POSTGRES_DB=appdb 
    - POSTGRES_USER=root 
    - POSTGRES_PASSWORD=example
    - POSTGRES_URL=postgres://root:example@postgres-test:5432/appdb
    - MINIO_SERVER_URL=http://minio-test:9000
    - MINIO_ROOT_USER=testuser
    - MINIO_ROOT_PASSWORD=password
    - REDIS_HOST=redis-test
    - REDIS_PORT=6379
    - REDIS_PASSWORD=password
    - MONGODB_URL=mongodb://root:example@mongodb-test:27017
    - MONGODB_NAME=my420_ca_db
    - ZOOM_VIDEO_SDK_KEY=a_key 
    - ZOOM_VIDEO_SDK_SECRET=a_key
    - ZOOM_API_KEY=a_key
    - ZOOM_API_SECRET=a_key
    - IS_MY420=true
  networks:
      - frontend-net 
      - backend-net 

# Frontend
x-frontend-base: &frontend_base 
    build: 
      context: ./frontend
      dockerfile: Dockerfile.test
    networks:
      - frontend-net

services:
  postgres-test:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: appdb
    networks:
      - backend-net
      - db-net
    profiles:
      - test
      - database
      - test_backend_integration_watch
      - test_frontend_integration_watch
      - test_e2e_watch

  dbmate-test:
    image: amacneil/dbmate
    depends_on:
      - postgres-test
    environment:
      - DATABASE_URL=postgres://root:example@postgres-test:5432/appdb?sslmode=disable
    volumes:
      - ./db/migrations:/db/migrations
    networks:
      - db-net
    profiles:
      - test
      - database
      - test_backend_integration_watch
      - test_frontend_integration_watch
      - test_e2e_watch
    command: ["--wait","up"]

  redis-test:
    image: redis:7
    restart: unless-stopped
    volumes: 
      - redis_data_test:/data
    networks: 
      - backend-net
    environment: 
      REDIS_HOST: redis-test
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    command: sh -c 'redis-server --requirepass password'
    profiles:
      - test
      - database
      - test_backend_integration_watch
      - test_frontend_integration_watch
      - test_e2e_watch

  minio-test:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"   # API & SDK access
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: http://minio-test:9000
    volumes:
      - minio_data_test:/data
    networks:
      - backend-net
      - db-net
    profiles:
      - test
      - database
      - test_backend_integration_watch
      - test_frontend_integration_watch
      - test_e2e_watch
    command: server /data --console-address ":9001" --address ":9000"

  minio-init-test:
    image: minio/mc:latest
    depends_on:
      - minio-test
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio-test:9000 testuser password --api S3v4 
      "
    networks:
      - backend-net
      - db-net
    profiles:
      - test
      - database
      - test_backend_integration_watch
      - test_frontend_integration_watch
      - test_e2e_watch

  mongodb-test:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_test:/data/db
    profiles:
      - test
      - database
      - test_backend_integration_watch
      - test_frontend_integration_watch
      - test_e2e_watch
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example
    networks:
      - backend-net

  backend-dummy: 
    build: 
      context: ./backend
      dockerfile : Dockerfile.test
    env_file: 
    - path: .env
      required: false
    environment:
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_SECRET=STUFRZH-MKLFj4j-6c9Z50WNWkvd9uqiWQJOpeCtI9Q
      - MFA_ENCRYPTION_KEY=7CrUl1rG4NBNk4bSV2uU7RW79Z_dRdvrrZn3Eqgytqg=
      - ALLOWED_ORIGINS=http://localhost:3000
      - APP_NAME=dummy
      - APP_URL=http://localhost:5174 
      - DEBUG=true
      - ENVIRONMENT=dev
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-sk-ant-dummy-key-for-testing}
      - SUPPORT_EMAIL=email@exmaple.com
      - ENVIRONMENT=Testing
      - SMTP_EMAIL=email@exmaple.com
      - SMTP_PASSWORD=password
      - SMTP_SERVER=mail.privateemail.com
      - POSTGRES_HOST=postgres-test
      - POSTGRES_PORT=5432
      - POSTGRES_DB=appdb 
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=example
      - POSTGRES_URL=postgres://root:example@postgres-test:5432/appdb
      - MONGODB_URL=mongodb://root:example@mongodb-test:27017
      - MONGODB_NAME=my420_ca_db
      - MINIO_SERVER_URL=http://minio-test:9000
      - MINIO_ROOT_USER=testuser
      - MINIO_ROOT_PASSWORD=password
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - ZOOM_VIDEO_SDK_KEY=a_key 
      - ZOOM_VIDEO_SDK_SECRET=a_key
      - ZOOM_API_KEY=a_key
      - ZOOM_API_SECRET=a_key
      - IS_MY420=true
    volumes:
      - ./scripts/wait-for-db.sh:/scripts/wait-for-db.sh
      - ./backend:/backend 
      - dummy_logs_test:/logs
    profiles:
      - backend
      - test_frontend_integration_watch
    networks:
      - frontend-net 
      - backend-net 
    ports:
      - 8002:8000
    entrypoint: ["/scripts/wait-for-db.sh"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Unit tests
  backend_unit_tests: 
    <<: *backend_base
    profiles:
      - test
      - test_unit 
      - test_backend 
      - test_backend_unit
    volumes:
      - ./backend/app:/backend/app 
      - ./backend/tests:/backend/tests
    command: "python -m unittest discover tests.unit"

  backend_unit_tests_watch: 
    <<: *backend_base
    profiles:
      - test_backend_unit_watch
    volumes:
      - ./backend/app:/backend/app 
      - ./backend/tests:/backend/tests
    command: >
      sh -c "while true; do
               python -m unittest discover tests.unit;
               inotifywait -e modify,create,delete -r /backend/app /backend/tests;
             done"

  frontend_unit_tests: 
    <<: *frontend_base
    profiles:
      - test
      - test_unit 
      - test_frontend
      - test_frontend_unit
    volumes:
      - ./frontend:/frontend
      - node_modules_test:/frontend/node_modules
    command: sh -c  "npm run test:unit"

  frontend_unit_tests_watch: 
    <<: *frontend_base
    profiles:
      - test_frontend_unit_watch
    volumes:
      - ./frontend:/frontend
      - node_modules_test:/frontend/node_modules
    command: >
      sh -c "while true; do
              npm run test:unit:watch; 
              inotifywait -e modify,create,delete -r /frontend/src /frontend/tests;
             done"

  # Integration tests 
  backend_integration_tests: 
    <<: *backend_base
    volumes:
      - ./scripts/wait-for-db.sh:/scripts/wait-for-db.sh
      - ./backend/app:/backend/app 
      - ./backend/tests:/backend/tests
      - backend_logs_test:/logs
    profiles:
      - test
      - test_integration 
      - test_backend 
      - test_backend_integration
    ports:
      - 8001:8000
    entrypoint: ["/scripts/wait-for-db.sh"]
    command: "python -m unittest discover tests.integration"

  backend_integration_tests_watch: 
    <<: *backend_base
    volumes:
      - ./scripts/wait-for-db.sh:/scripts/wait-for-db.sh
      - ./backend/app:/backend/app 
      - ./backend/tests:/backend/tests 
      - backend_logs_test:/logs
    profiles:
      - test_backend_integration_watch
    ports:
      - 8001:8000
    entrypoint: ["/scripts/wait-for-db.sh"]
    command: >
      sh -c "while true; do
               python -m unittest discover tests.integration;
               inotifywait -e modify,create,delete -r /backend/app /backend/tests;
             done"

  frontend_integration_tests: 
    <<: *frontend_base
    environment:
      - BACKEND_URL=http://backend-dummy:8000
      - VITE_API_BASE_URL=http://backend-dummy:8000
    profiles:
      - test
      - test_integration 
      - test_frontend
      - test_frontend_integration
    ports:
      - 5174:5173
    volumes:
      - ./scripts/wait-for-backend.sh:/scripts/wait-for-backend.sh
      - ./frontend:/frontend
      - node_modules_test:/frontend/node_modules
    entrypoint: ["/scripts/wait-for-backend.sh"]
    command: sh -c  "npm run test:integration"


  frontend_integration_tests_watch: 
    <<: *frontend_base
    environment:
      - BACKEND_URL=http://backend-dummy:8000
      - VITE_API_BASE_URL=http://backend-dummy:8000
      - TZ=America/Toronto
    profiles:
      - test_frontend_integration_watch
    ports:
      - 5174:5173
    volumes:
      - ./scripts/wait-for-backend.sh:/scripts/wait-for-backend.sh
      - ./frontend:/frontend
      - node_modules_test:/frontend/node_modules
    entrypoint: ["/scripts/wait-for-backend.sh"]
    command: > 
       sh -c "while true; do
                npm run test:integration:watch;  
                inotifywait -e modify,create,delete -r /frontend/src /frontend/tests;
              done"
    # npm run test:integration:watch --file=tests/integration/analytics.test.js; 

volumes:
  mongo_data_test:
  postgres_data_test:
  node_modules_test:
  minio_data_test:
  redis_data_test:
  backend_logs_test:
  dummy_logs_test:

networks:
  frontend-net:
    driver: bridge
 
  db-net:
    driver: bridge

  backend-net:
    driver: bridge



