services:
  postgres_dev:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./certs:/certs:ro
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: appdb
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
      POSTGRES_HOST_AUTH_METHOD: md5
    networks:
      - backend-net
      - db-net
    profiles:
      - dev
      - dev_backend 
      - dev_frontend 
      - db
    command: |
      postgres 
        -c ssl=on 
        -c ssl_cert_file=/certs/server.crt 
        -c ssl_key_file=/certs/server.key 
        -c ssl_ca_file=/certs/ca.crt 
        -c ssl_min_protocol_version=TLSv1.2

  dbmate_dev:
    image: amacneil/dbmate
    depends_on:
      - postgres_dev
    environment:
      - DATABASE_URL=postgres://admin:example@postgres_dev:5432/appdb?sslmode=require
    volumes:
      - ./db/migrations:/db/migrations
    networks:
      - db-net
    profiles:
      - dev
      - dev_backend 
      - dev_frontend 
      - db
    command: ["--wait","up"]

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    profiles:
      - dev 
      - backend 
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example
    networks:
      - backend-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev 
    environment:
      - POSTGRES_HOST=postgres_dev
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=appdb 
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=example
      - DATABASE_URL=postgres://admin:example@postgres_dev:5432/appdb?sslmode=require
      - ALLOWED_ORIGINS=[http://localhost:5173]
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_SECRET=STUFRZH-MKLFj4j-6c9Z50WNWkvd9uqiWQJOpeCtI9Q
      - JWT_REFRESH_SECRET=STUFRZH-MKLFj4j-6c9Z50WNWkvd9uqiWQJOpeCtI9Q
      - MFA_ENCRYPTION_KEY=7CrUl1rG4NBNk4bSV2uU7RW79Z_dRdvrrZn3Eqgytqg=
      - APP_URL=http://localhost:5173 
      - APP_NAME=testing 
      - DEBUG=True
      - MONGO_URL=mongodb://root:example@mongodb:27017
      - DB_NAME=my420_ca_db
      - ENVIRONMENT=dev
      - PYTHONPATH=/backend
      - CA_FILE=/certs/ca.crt
    env_file:
      - .env
    networks:
      - backend-net 
      - frontend-net
    profiles:
      - dev
      - dev_backend 
    ports:
      - 8000:8000
    volumes:
      - ./scripts/wait-for-db.sh:/scripts/wait-for-db.sh
      - ./scripts/create_admin.sh:/scripts/create_admin.sh
      - ./backend/app:/backend/app
      - ./backend/scripts:/backend/scripts 
      - ./certs:/certs:ro
    entrypoint: ["/scripts/create_admin.sh"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" , "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev 
    env_file:
      - .env
    environment: 
      - VITE_API_BASE_URL=http://localhost:8000
    networks:
      - frontend-net
    ports:
      - 5173:5173
    profiles:
      - dev 
      - frontend
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: > 
      sh -c " 
        npm install;
        npm run dev -- --host 0.0.0.0 --port 5173
      "

volumes:
  postgres_data:
  node_modules:
  mongo_data:

networks:
  frontend-net:
    driver: bridge
 
  db-net:
    driver: bridge

  backend-net:
    driver: bridge



