services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: 
      - .env
    networks:
      - backend-net
    profiles:
      - dev 
      - prod 
    volumes:
      - mongo_data:/data/db

  backend: 
    build: ./backend
    env_file: 
      - .env
    depends_on:
      - mongodb
    networks:
      - backend-net 
      - frontend-net
    profiles:
      - dev 
      - prod
    volumes:
      - ./persistent-data:/app/persistent-data
      - ./production-protected:/app/.production-protected
      - ./scripts:/app/scripts
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]


  frontend-builder:
    build: ./frontend
    env_file: 
      - .env
    profiles:
      - dev 
      - prod
    volumes:
      - frontend_dist:/dist
    command: >
      sh -c "
        npm run build &&
        cp -r build/. /dist
      "

  nginx-dev:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    profiles:
      - dev
    networks:
      - frontend-net
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro

  nginx-setup:
    image: nginx:alpine
    ports:
      - 80:80
    env_file:
      - .env
    profiles:
      - staging
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.setup.conf:/etc/nginx/templates/nginx.conf.template

  certbot-setup:
    image: certbot/certbot
    env_file:
      - .env
    depends_on: 
      - nginx-setup
    profiles:
      - staging
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - ./scripts/cert_check.sh:/scripts/cert_check.sh:ro
    entrypoint: ["sh"]
    command: ["/scripts/cert_check.sh"]
  
  nginx-prod:
    image: nginx:alpine 
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    profiles:
      - prod
    networks:
      - frontend-net
    depends_on:
      - backend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.prod.conf:/etc/nginx/templates/nginx.conf.template

volumes: 
  frontend_dist:
  mongo_data:
  certbot-etc:
  certbot-var:
  certbot-www:

networks:
  frontend-net:
    driver: bridge
 
  backend-net:
    driver: bridge

  # db-net:
  #   driver: bridge
  #

