#syntax=docker/dockerfile:1 

FROM python:3.11-slim

# Needed to poll database to ensure its running before starting
RUN apt-get update && apt-get install -y postgresql-client &&  apt-get install -y inotify-tools && apt-get clean

# Set working directory
WORKDIR /backend

# Copy only requirements first for better caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

